version: "3.8"

services:
#-------------------------------------Web--------------------------------------#

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./requirements/Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./requirements/Nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    depends_on:
      - django

  django:
    container_name: django
    build: web/
    env_file:
      - .env
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost
      - ELASTICSEARCH_HOST=elasticsearch
      - LOGSTASH_HOST=logstash
    volumes:
    - "./web/:/usr/src/app"
    networks:
      - app_network
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
      - elasticsearch
      - logstash
    restart: on-failure

#-------------------------------Base de donnee---------------------------------#

  postgresql:
    image: postgres:13
    container_name: postgresql
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"
    restart: on-failure

  postgres_exporter:
    image: wrouesnel/postgres_exporter
    container_name: postgres_exporter
    env_file:
      - .env
    environment:
      - DATA_SOURCE_NAME=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - postgresql
    ports:
      - "9187:9187"
    networks:
      - app_network

#----------------------------------ELK stack-----------------------------------#

  elasticsearch:
    image: elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - network.host=0.0.0.0
      - http.port=9200
      - xpack.security.enabled=false
    volumes:
      - ELKdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app_network

  logstash:
    image: logstash:8.13.4
    container_name: logstash
    depends_on:
      - elasticsearch
    environment:
      - xpack.monitoring.elasticsearch.hosts=http://elasticsearch:9200
      - path.data=/usr/share/logstash/data
      - config.reload.automatic=true
      - config.reload.interval=3s
    volumes:
      - ./requirements/ELK/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./requirements/ELK/test.json:/usr/share/logstash/test.json
    ports:
      - "5044:5044"
      - "9600:9600"
    networks:
      - app_network

  kibana:
    image: kibana:8.13.4
    container_name: kibana
    depends_on:
      - logstash
    networks:
      - app_network
    ports:
      - "5601:5601"
    environment:
      - server.name=kibana
      - server.host=0.0.0.0
      - elasticsearch.hosts=http://elasticsearch:9200
      - logstash.hosts=http://logstash:9600
      - xpack.monitoring.ui.container.elasticsearch.enabled=true
      - xpack.monitoring.collection.enabled=true

#----------------------------------Monitoring----------------------------------#

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./requirements/prometheus:/etc/prometheus/
    ports:
      - "9090:9090"
    networks:
      - app_network
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - app_network
    restart: unless-stopped

#----------------------------------HashiCorpV----------------------------------#

  # HashiCorpVault:
  #   version: '3.6'
  #   services:
  # vault:
  #   image: vault:1.13.3
  #   container_name: vault
  #   restart: on-failure:10
  #   ports:
  #     - "8201:8201"
  #   environment:
  #     VAULT_ADDR: 'https://0.0.0.0:8201'
  #     VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address": "0.0.0.0:8201","tls_disable":"0", \
  #                         "tls_cert_file":"/HashiCorpVault/requirements/certificate.pem", \
  #                         "tls_key_file":"/HashiCorpVault/requirements/key.pem"}}], \
  #                         "default_lease_ttl": "168h", "max_lease_ttl": "720h"}, "ui": true}'
  #     VAULT_DEV_ROOT_TOKEN_ID: '3f6104e8-af38-48fd-b2d0-475797cc04a5'
  #     VAULT_TOKEN: 'hvs.07jE2OHP3ysgy1Y9pdkwKT16'
  #   cap_add:
  #     - IPC_LOCK
  #   volumes:
  #     - ./HashiCorpVault:/data
  #   healthcheck:
  #     retries: 5
  #   command: server -dev -dev-root-token-id="3f6104e8-af38-48fd-b2d0-475797cc04a5"
  #   networks:
  #     - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db:
    driver: local
  ELKdata:
    driver: local
  prom_data:
    driver: local
  HashiCorp:
    driver: local
