# Generated by Django 3.2.25 on 2024-08-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0002_auto_20240815_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='a2f',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='a2f_code',
            field=models.IntegerField(default=0),
        ),
    ]
