# Generated by Django 3.2.25 on 2024-08-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0003_auto_20240826_1413'),
        ('user_manage', '0003_remove_customuser_is_onsite'),
    ]

    operations = [
    ]
