# Generated by Django 3.2.25 on 2024-08-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0004_merge_20240829_0711'),
        ('user_manage', '0004_merge_20240829_0715'),
    ]

    operations = [
    ]
