# Generated by Django 3.2.25 on 2024-08-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PongResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(default='', max_length=255)),
                ('player2', models.CharField(default='', max_length=255)),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('winner', models.CharField(default='', max_length=255)),
                ('loser', models.CharField(default='', max_length=255)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
