# Generated by Django 3.2.25 on 2024-08-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pongresult',
            name='loser',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pongresult',
            name='player1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pongresult',
            name='player2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pongresult',
            name='winner',
            field=models.CharField(default='', max_length=255),
        ),
    ]
