# Generated by Django 3.2.25 on 2024-08-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
