# Generated by Django 3.2.25 on 2024-08-27 16:46

from django.conf import settings
from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('live_chat', '0038_auto_20240827_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='onlineusers',
            name='users_online',
            field=models.ManyToManyField(blank=True, related_name='onsite', to=settings.AUTH_USER_MODEL),
        ),
    ]
