# Generated by Django 3.2.25 on 2024-08-29 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_chat', '0039_alter_chatgroup_group_name'),
        ('live_chat', '0069_alter_chatgroup_group_name'),
    ]

    operations = [
    ]
