# Generated by Django 3.2.25 on 2024-08-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_chat', '0070_merge_20240829_0711'),
        ('live_chat', '0072_alter_chatgroup_group_name'),
    ]

    operations = [
    ]
