# Generated by Django 3.2.25 on 2024-08-28 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_manage', '0003_auto_20240826_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_manage.customuser')),
            ],
            options={
                'abstract': False,
            },
            bases=('user_manage.customuser',),
        ),
    ]
