name: Deploy Django Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64 --file projet/srcs/web/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/your-django-app:latest --push projet/srcs/web

    - name: Create .env file
      run: |
        echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> projet/srcs/.env
        echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> projet/srcs/.env
        echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> projet/srcs/.env
        echo DJANGO_ADMIN_USER=${{ secrets.DJANGO_ADMIN_USER }} >> projet/srcs/.env
        echo DJANGO_ADMIN_MAIL=${{ secrets.DJANGO_ADMIN_MAIL }} >> projet/srcs/.env
        echo DJANGO_ADMIN_PASS=${{ secrets.DJANGO_ADMIN_PASS }} >> projet/srcs/.env
        echo UID_42=${{ secrets.UID_42 }} >> projet/srcs/.env
        echo SECRET_42=${{ secrets.SECRET_42 }} >> projet/srcs/.env

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Deploy with Docker Compose
      run: docker-compose -f projet/srcs/docker-compose.yml up -d
