name: Deploy Django Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64 --file projet/srcs/web/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/your-django-app:latest --push projet/srcs/web

    - name: Create .env file
      run: |
        echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
        echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
        echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
        echo DJANGO_ADMIN_USER=${{ secrets.DJANGO_ADMIN_USER }} >> .env
        echo DJANGO_ADMIN_MAIL=${{ secrets.DJANGO_ADMIN_MAIL }} >> .env
        echo DJANGO_ADMIN_PASS=${{ secrets.DJANGO_ADMIN_PASS }} >> .env
        echo UID_42=${{ secrets.UID_42 }} >> .env
        echo SECRET_42=${{ secrets.SECRET_42 }} >> .env

    - name: Deploy with Docker Compose
      run: docker-compose -f docker-compose.yml up -d
