name: Restrict Merge to Main

on:
  pull_request:
    branches:
      - main

jobs:
  restrict-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is from Dev branch
        run: |
          if [[ "${{ github.head_ref }}" != "Dev" ]]; then
            echo "PRs to main must come from Dev branch only!"
            exit 1
          fi
